host: https://hasannelta.testrail.io
project: TestNG
username: habdullah@nelta.de
password: 113CTms/Nlv8xRgh4qhz
#api: 6y9DdTeLJChrtJHi0DUN-vmolkjbiXfgg9kKXI406
title: testcase
file: C:\Users\Hasan Abdullah\IdeaProjects\testng\report_sample\TEST-TestSuite.xml
